const STORAGE_NAME = '@gameplay';

const COLLECTION_USER = `${STORAGE_NAME}:user`;
const COLLECTION_APPOINTMENTS = `${STORAGE_NAME}:appointments`;

export {
  COLLECTION_USER,
  COLLECTION_APPOINTMENTS
}